GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "mluukkai3",
    "name": "Matti Luukkainen",
    "password": "salainen"
}

###
DELETE http://localhost:3003/api/users/688b9e1e148acb92b10368cd
Content-Type: application/json