GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3ZjUxNjEwYTIzMDAzNGUxMWZjNjIzYSIsImlhdCI6MTc0NDE0NzA0MX0.Azsk_klJ2QGACEk2sCx3AVDTRcEWZh4Ej3t_NbzLkFM

{
    "title": "My first blog",
    "author": "Dan Roswell",
    "url": "urlthis",
    "likes": 5
}