GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Dan Roswell",
    "number": "12345"
}

###
POST https://full-stack-open-amdx.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Dan Roswell",
    "number": "12345"
}